apiVersion: v2
name: tero-edge
description: A Helm chart for Kubernetes
type: application
icon: >-
  https://docs.usetero.com/mintlify-assets/_mintlify/favicons/tero-0926be64/y5F_7SW7tjbC22aW/_generated/favicon/apple-touch-icon.png
version: 0.3.0
appVersion: 1.18.0
