{{- include "tero-edge.validateTeroAuth" . }}
{{- if and .Values.tero.apiKey (not .Values.tero.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tero-edge.apiKeySecretName" . }}
  labels:
    {{- include "tero-edge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "tero-edge.apiKeySecretKey" . }}: {{ .Values.tero.apiKey | quote }}
{{- end }}
